### PR TITLE
fix(deps): bump @octokit/core from 3.5.1 to 3.6.0

### LINKED ISSUE #378: Dependency on node-fetch version 2.6.5
`node-fetch` is subject to a high severity vulnerability: https://github.com/advisories/GHSA-r683-j2x4-v87g

This should be fixable by updating to `"@octokit/core": "^3.6.0"`

### PR DESCRIPTION
**Pull request by thomas-maqua-db**
This resolves #378

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by thomas-maqua-db** [comment]
Are any additional manual steps necessary here?

A merge and a new release would be greatly appreciated.

**Comment by wolfy1339** [comment]
There isn't any steps. It's a problem on Github's side.

For some reason, your PR isn't triggering tests and we require tests to pass in order to merge PRs.

**Comment by thomas-maqua-db** [comment]
This is probably due to the fact that the test workflow runs on push, but this is a PR from a forked repository.

Could you maybe push these changes to a new branch on this repository and create a new PR?

**Comment by oscard0m** [comment]
@thomas-maqua-db can you trigger the CI again (with an empty commit, rebasing from main branch, etc or other options?)

**Comment by Mussee** [comment]
Hi

**Pull request merged**
