### PR TITLE
fix: support all `GITHUB_` environment variables for proxies

### LINKED ISSUE #342: Extended Proxy Support
I see #329 added proxy environment support but it is a very simple implementation that only handles `https_proxy`.

The person that maintains the proxy agent has an expanded version, https://github.com/TooTallNate/node-proxy-agent, which should do a better job of handling `https_proxy` and also `no_proxy` which isn't currently being handled here.

Basic testing seems to show the following works as expected with the core octokit library, adding in proxy depending on both the `https_proxy` and `no_proxy` variables.

```javascript
  const ProxyAgent = require('proxy-agent');

  const octokitProxy = new Octokit({
    request: { agent: new ProxyAgent()}
  })
```

### PR DESCRIPTION
**Pull request by steve-norman-rft**
Starter code to move to proxy-agent for proxy support.

I personally don't like the changes to the unit test as you don't really know if it is using the proxy servers or not.  Tried a few variants to spy on the `ProxyAgent` and also the `proxy-from-env` module but couldn't get anything to work. 

Closes #342.

### CODE REVIEW

**Comment by steve-norman-rft** [comment]
@droidpl - As discussed earlier.

**Comment by gr2m** [comment]
Let me know when you are ready from your side, or if you need any help

**Comment by steve-norman-rft** [comment]
Hard to test this as I need proxy configuration for the runner to work.  But I've built the latest version of this change and packaged that with an action.  

It works as expected when running behind the proxy so appears to be picking up the environment variables as expected.  

Created a quick test using a GitHub hosted runner and that worked as well so that should have been without any proxy settings being used.

**Review by gr2m — APPROVED** [review]
Alrighty, thanks for testing it, as folks are currently blocked by it, I say we move on with it :)

**Pull request merged**
