### PR TITLE
[maint]: update links to CODE_OF_CONDUCT in issue templates

### LINKED ISSUE #573: [MAINT]: Links to CODE_OF_CONDUCT in issue templates are broken
### Describe the need

Each issue template provides a link to CODE_OF_CONDUCT near end.

Currently such link jumps to a wrong url, https://github.com/octokit/action.js/issues/CODE_OF_CONDUCT.md.
https://github.com/octokit/action.js/blob/7b19341bf70496a2a43cb96695f5e86ab4621000/.github/ISSUE_TEMPLATE/maintenance.yml?plain=1#L46

The expected destination is https://github.com/octokit/action.js/blob/main/CODE_OF_CONDUCT.md.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by muzimuzhi**
Resolves #573

----

### Before the change?

Links to CODE_OF_CONDUCT in each issue templates jumps to a wrong url https://github.com/octokit/action.js/issues/CODE_OF_CONDUCT.md

### After the change?

Jump to the correct url https://github.com/octokit/action.js/blob/main/CODE_OF_CONDUCT.md

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]
Thank you!

**Comment by kfcampbell** [comment]
These Actions are automatically updated whenever anything changes in the [octokit/.github repo](https://github.com/octokit/.github). I wonder if there's a way to make a generic update there that would correct this behavior across all our repos.

**Comment by muzimuzhi** [comment]
> These Actions are automatically updated whenever anything changes in the [octokit/.github repo](https://github.com/octokit/.github). I wonder if there's a way to make a generic update there that would correct this behavior across all our repos.

Homebrew uses a [sync-templates-and-ci-config.yml](https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/sync-templates-and-ci-config.yml) workflow to keep templates and CI configs in downstream repositories `Homebrew/homebrew-cask-fonts` and `Homebrew/homebrew-cask-fonts` be sync with upstream repository `Homebrew/homebrew-cask`.

Then
- All (manual) changes to these templates and CI configs are directed to upstream repo.
- Each time those in upstream repo changed, that workflow is triggered which opens PR in downstream repos.

**Comment by muzimuzhi** [comment]
> These Actions are automatically updated whenever anything changes in the [octokit/.github repo](https://github.com/octokit/.github). I wonder if there's a way to make a generic update there that would correct this behavior across all our repos.

I will try.

**Comment by muzimuzhi** [comment]
> These Actions are automatically updated whenever anything changes in the [octokit/.github repo](https://github.com/octokit/.github). I wonder if there's a way to make a generic update there that would correct this behavior across all our repos.

@kfcampbell I found no issue templates in repo [octokit/.github repo](https://github.com/octokit/.github) you linked, but in [nickfloyd/repo-meta](https://github.com/nickfloyd/repo-meta).

Is it the correct repo?

One workaround I've found is
```diff
-[Code of Conduct](CODE_OF_CONDUCT.md)
+[Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
```

I've pushed these changes to my fork so you can try in https://github.com/muzimuzhi/repo-meta/issues/new/choose.

It can be applied to all repos having a `CODE_OF_CONDUCT.md` in root directory and using `main` as default branch.

I also added a comment to the official feedback for Issue Forms beta and Issue Templates, see https://github.com/orgs/community/discussions/63402#discussioncomment-8042730.

**Comment by kfcampbell** [comment]
Ahh, maybe we used [an octoherd script](https://github.com/octoherd) ([this one](https://github.com/kfcampbell/create-or-update-pull-request-action)?) to add each action, in which case we'd have to do something similar or manual updates to fix our other repos. I think it's unlikely our team gets to this in the near future, but please feel free to submit any PRs you feel so inclined to. Thanks for following up!

**Comment by muzimuzhi** [comment]
> These Actions are automatically updated whenever anything changes in the [octokit/.github repo](https://github.com/octokit/.github).

> Ahh, maybe we used [an octoherd script](https://github.com/octoherd) ([this one](https://github.com/kfcampbell/create-or-update-pull-request-action)?) to add each action, ...

@kfcampbell Err the files I modified in this PR are not actions, but issue and pull request templates.

**Comment by kfcampbell** [comment]
You're correct; I misspoke!

**Pull request merged**
